version: '3'

services:
  webserver:
    build:
      context: ./bin/php74
    container_name: l4d2_stats-php74
    restart: always
    ports:
      - 8086:80
    links:
      - database
    volumes:
      - ./www:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/vhosts:/etc/apache2/sites-enabled
      - ./logs/apache2:/var/log/apache2
  database:
    build:
      context: ./bin/mysql
    container_name: l4d2_stats-database
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: <password>
      MYSQL_DATABASE: l4d2_stats
      MYSQL_USER: l4d2_stats
      MYSQL_PASSWORD: <password>
