version: '3'
services:
  php-apache:
    image: php:7.4-apache
    ports:
      - 8086:80
    volumes:
      - ./web:/var/www/html:z
    links:
      - 'mariadb'
  mariadb:
    image: mariadb:5
    environment:
      MYSQL_USER: l4d2_stats
      MYSQL_PASSWORD: l4d2_stats
      MYSQL_DATABASE: l4d2_stats
      MYSQL_ROOT_PASSWORD: l4d2_stats
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql
volumes:
    mariadb:
